---
# tasks file for webserver

- name: "installing webserver package - httpd"
  package:
          name: "httpd"
          state: present

- name: "installing php software"
  package:
          name: "php"
          state: present

- name: "copying the web page"
  copy:
          src: "index.php"
          dest: "/var/www/html/index.php"

- name: "starting webserver"
  service:
          name: "httpd"
          state: restarted
